### ISSUE TITLE
Setup/Create Server

### ISSUE THREAD

**Issue by watkincw** [ThManHimself/book-tracker#2]

**Comment by watkincw** [comment]
I've been working on this part of the project this morning so far. My goal is to just start the server.

I think the server.js file is (for the most part at least) ready to go. Might need to make some tweaks to it as we go. At the moment, things are commented out in there so I could do some testing to trace where I need to start/what files I need written in before the server will run. In the Colton branch there is a start to the ./config/connection.js file, but its not finished/working yet. Having trouble finding out why the `const Sequelize = require('sequelize');` doesnt seem to be connected the right way. The other Sequelize variable calls lower in the file also dont seems to be connecting to sequelize yet either, but of course that because the Sequelize definition isnt yet working either. Feel free to grab the code from the Colton branch and work with it from there if you know of a way to make the server start up(using the npm command). If you end up grabbing the code make sure to work on it in a branch of your own as well to keep the work separate and less confusing to work in!(just a friendly reminder! :) )

**Comment by bcassellius** [comment]
Worked on together in zoom - Got it working!!!
