### ISSUE TITLE
Develop the Front-End

### ISSUE THREAD

**Issue by bcassellius** [ThManHimself/book-tracker#5]
- [x] Use a css program (bootstrap/materialize...)
- [x] Create a smooth UI
- [x] #11
- [x] #6
- [x] Interactive

**Comment by watkincw** [comment]
As for the styling, I recommend switching from using the npm versions of materialize(or whatever css framework you decide to use) to just importing the CDN version of the framework that gets decided on. Whichever is decided on is fine with me. If anyone has any objections let the group know but for simplicity sake, just to get some styling on the pages before the due date I think it will be easiest and fastest to just import a CDN like we did in the early in the bootcamp. Also, its worth noting that using the materialize CDN **DOES** count as a "New Technology", if you're concerned about that aspect of it. In the presentations a few groups noted that as their new tech.

(Although its been spoken about in class, when it refers to "Use at least one new library, package, or technology that we haven’t discussed", it is talking about something new that hasn't been used in one of the modules or projects in the modules. The Materialize CDN falls under that category.)
